# Generated by Django 4.0.3 on 2022-06-29 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_category_products_substitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to=settings.AUTH_USER_MODEL),
        ),
    ]
