# Generated by Django 4.0.3 on 2022-06-29 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_substitute_product_alter_substitute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
