# Generated by Django 4.0.3 on 2022-06-29 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_substitute_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substitute',
            unique_together={('product', 'user')},
        ),
    ]
